
[[redirects]]
  from = "/latest/*"
  to = "https://github.com/vmware-tanzu/pinniped/releases/download/v0.4.1/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "https://github.com/vmware-tanzu/pinniped/releases/download/:splat"
  status = 302
  force = true
